apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: kube-logging
spec:
  serviceName: elasticsearch
  replicas: $NUMBER_PODS
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        # image: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        env:
          - name: discovery.seed_hosts
            value: elasticsearch
          - name: discovery.type
            value: single-node 
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: client
